name: Defi

on:
  push:
    branches: [ master ]
  repository_dispatch:

defaults:
  run:
    working-directory: defi
    
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      defi: ${{ steps.filter.outputs.defi }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          defi:
            - 'defi/**'
  test:
    needs: changes
    if: ${{ needs.changes.outputs.defi == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.5.1'
    - run: npm ci
    - run: git submodule update --init --recursive
    - run: cd DefiLlama-Adapters && git checkout main && git pull
    - name: Run tests
      run: npm t data
      env:
        ETHEREUM_RPC: ETHEREUM_RPC
  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.defi == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.5.1'
    - run: npm ci
    - run: git submodule update --init --recursive
    - run: cd DefiLlama-Adapters && git checkout main && git pull
    - run: npm ls -prod -json -depth=1
    - name: Deploy infrastructure stack
      run: npm run deploy:prod
      env:
        ETHEREUM_RPC: ${{ secrets.ETHEREUM_RPC }}
        POLYGON_RPC: ${{ secrets.POLYGON_RPC }}
        BSC_RPC: ${{ secrets.BSC_RPC }}
        FANTOM_RPC: ${{ secrets.FANTOM_RPC }}
        ARBITRUM_RPC: ${{ secrets.ARBITRUM_RPC }}
        OPTIMISM_RPC: ${{ secrets.OPTIMISM_RPC }}
        XDAI_RPC: ${{ secrets.XDAI_RPC }}
        HARMONY_RPC: ${{ secrets.HARMONY_RPC }}
        MOONRIVER_RPC: ${{ secrets.MOONRIVER_RPC }}
        OUTDATED_WEBHOOK: ${{ secrets.OUTDATED_WEBHOOK }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SPIKE_WEBHOOK: ${{ secrets.SPIKE_WEBHOOK }}
        CLOUDWATCH_WEBHOOK_URL: ${{ secrets.CLOUDWATCH_WEBHOOK_URL }}
        DROPS_WEBHOOK: ${{ secrets.DROPS_WEBHOOK }}
        EULER_MONGODB_APIKEY: ${{ secrets.EULER_MONGODB_APIKEY }}
